### ISSUE TITLE
Issue with YAML/JSON file: "incomplete config"

### ISSUE THREAD

**Issue by johnricco** [fitnr/everylotbot#1]
The following command:

`everylot everylotphilly lots.db --config bots.yaml`

returns the following error:

`ValueError: Incomplete config. Missing ['consumer_key', 'consumer_secret', 'key', 'secret']`

This is not strictly a .yaml issue; I get the same error with a .json file. Nor is it the result of a misplaced or empty file, as these issues return different errors. 

One possibly useful piece of information: my account name and app name are the same ("everylotphilly").

**Comment by fitnr** [comment]
This was a bug in the cli code. Please download the latest version and it should work
