### ISSUE TITLE
"TypeError: zip argument #2 must support iteration"

### ISSUE THREAD

**Issue by johnricco** [fitnr/everylotbot#2]
The `everylot` command is returning the following error:

> Traceback (most recent call last):
>   File "/Users/johnricco/anaconda/bin/everylot", line 9, in <module>
>     load_entry_point('everylot==0.3.0', 'console_scripts', 'everylot')()
>   File "build/bdist.macosx-10.5-x86_64/egg/everylot/bot.py", line 45, in main
>   File "build/bdist.macosx-10.5-x86_64/egg/everylot/everylot.py", line 68, in **init**
> TypeError: zip argument #2 must support iteration

Which is pointing at this code:

`self.lot = dict(zip(keys, curs.fetchone()))`

Something is up with the `fetchone()` method. Doesn't appear to be a problem with my table, which look like this: 

![image](https://cloud.githubusercontent.com/assets/11996783/19323229/05276d72-908a-11e6-9b6b-f32096be5f84.png)

**Comment by johnricco** [comment]
I made two changed to the database: making `tweeted` a 0-1 integer column and fixed `long` to be `lon`. I have no issue now.

**Comment by fitnr** [comment]
Might want to look at the zip column too @johnricco  😄
