### ISSUE TITLE
Append ZoLa Link to Status

### ISSUE THREAD

**Issue by chriswhong** [fitnr/everylotbot#4]
The NYC Department of City Planning's Zoning and Land Use App contains composable URLs for every tax lot, and it would be rad to append a hyperlink to each everylotnyc tweet.

The format is:

`https://zola.planning.nyc.gov/lot/{borocode}/{block}/{lot}`

These are non-zero-padded numbers pulled directly from MapPLUTO.  I would do a pull request but I am not clear on whether these three attributes exist in your SQLite database.  (I assume you are using MapPLUTO or DTM, but not sure if you kept all of the attributes)

Anyway, let me know if you're interested.  If not, no biggie, and thanks for setting up this awesome tweet bot!

**Comment by fitnr** [comment]
Chris: you can't make pull requests on someone else's art.

**Comment by andycochran** [comment]
Pull requests _are_ art, but you're right Neil, this pull request is dumb.

**Comment by fitnr** [comment]
Thanks for the support Andy! I'm glad you agree. (And I hope you don't mind a little detournment, since this is an artistic setting, after all)
